### ISSUE TITLE
FunctionSubtree does not pass IElementType upto super

### ISSUE THREAD

**Issue by swissgrammie** [antlr/jetbrains#10]
I am new to antlr, intellij plugins and maven...so i figure i have done something wrong but i cant see it. 

Environment : 
Intellij IDEA 2016.1
JDK 1.8.0_73

I have cloned the jetbrains-plugin-sample
I have cloned, as a submodule, antlr/jetbrains

I have set the adapter/src directory as a source root in idea

I installed the latest antlr plugin and then set the antlr preferences for SampleLanguage.g4 to 
Auto-generate parsers upon save ENABLED
package : org.antlr.jetbrains.sample.parser
generate parse tree listener ENABLED
generate parse tree visitor ENABLED

I then hit "ctrl-shift-G" on the SampleLanguage.g4 file

I then set the gen directory as a source root for idea

Now compile and  I get a couple of errors
1. FunctionSubtree constructor isnt compatible with IdentifierDefSubtree (doesnt have IElementType)
2. VardefSubtree same error.

The IdentifierDefSubtree hides the ANTLRPsiNode c'tor so I just altered these 2 classes to inherit directly from ANTLRPsiNode, I know this probably breaks stuff down the line, in fact i know it does cause when i run the tests i get 7 failed, but all i want for my project is mylanguage syntax highlighting in intellij.

**Comment by parrt** [comment]
Hi.  sorry about that. I'm not sure what's up. I haven't worked on the plug-in for a few months but hope to get back to it soon.

**Comment by kshchepanovskyi** [comment]
There are few incompatibilities between library and sample plugin, I also faced with them and fixed in my pull requests (gradle integration).

KS

Apr 21, 2016 о 7:52 PM Terence Parr <notifications@github.com> написав(ла):

**Comment by swissgrammie** [comment]
@parrt thanks, I have everything i need for my plugin so no rush and being able to use antlr rather than bnf and jflex is great.
@kshchepanovskyi  thank you, I have taken a look at your stuff as well and put that on the todo list when i need to release anything.
